Yyx/123 reset tabs
gjwgit/rattleng pull request #146
Opened 2024-06-17 16:23 UTC by yixiangyin

# Pull Request Details

## What issue does this PR address

- [A one line description of this PR]

- Link to associated issue: #

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [ ] Added a reviewer

## Finalising

Once PR discussion is complete and reviewer has approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

2024-06-17 16:30 UTC, yixiangyin commented
home_tabs.dart is not used. Should we remove it in this pr?

2024-06-17 21:58 UTC, gjwgit requested changes
This pull request is "advertised" as fixing the reset tabs (essentially reset to the DATASET tab on a REST tap).

That works just fine and thanks for that.

However, this PR also includes some work in progress for #121. Could that work be split into a different branch please for separate discussion. Thanks. It looks great so far and I'll comment on some ideas in the issue #121.

Then I can merge this PR for #123.

2024-06-17 22:01 UTC, gjwgit commented on lib/panels/cluster/config.dart
Thanks for fixing these.

2024-06-17 22:02 UTC, gjwgit commented on lib/panels/tree/display.dart
Perhaps this into a different branch specific for panel navigation.

2024-06-17 22:03 UTC, gjwgit commented on lib/panels/tree/display.dart
> +}
You can set you IDE to always include a final new line in your files.

2024-06-17 22:06 UTC, gjwgit commented
I'll approve and merge this one with the extra "feature" but do aim to keep them as separate branches and PRs. Thanks

2024-06-17 22:06 UTC, merged

2024-06-18 05:23 UTC, yixiangyin commented
> This pull request is "advertised" as fixing the reset tabs (essentially reset to the DATASET tab on a REST tap).
> 
> That works just fine and thanks for that.
> 
> However, this PR also includes some work in progress for #121. Could that work be split into a different branch please for separate discussion. Thanks. It looks great so far and I'll comment on some ideas in the issue #121.
> 
> Then I can merge this PR for #123.

Apologies I just realised that. I will create one for 121.